name: Flutter My Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '请输入要发布的 tag'
        required: true
        default: 'sanlian'

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ github.event.inputs.tag }}
