name: Flutter My Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '请输入要发布的 tag'
        required: true
        default: 'sanlian'
      build-targets:
        description: '选择要构建的目标，用逗号分隔，如 all, windows, windows-flutter, windows-sciter, linux, linux-flutter, linux-sciter, ios, macos, android, flutter, sciter'
        required: false
        default: 'all'

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ github.event.inputs.tag }}
      build-targets: ${{ github.event.inputs.build-targets }}
